package vistas;

import modelo.Cliente;
import controladores.ClientesData;
import controladores.ProductoData;
import controladores.ProveedorData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Proveedor;

/**
 *
 * @author VIB
 */
public class Menu extends javax.swing.JFrame {

    Cliente c1 = new Cliente();
    ClientesData clienteD = new ClientesData();
    Proveedor p1 = new Proveedor();
    ProveedorData proveedorD = new ProveedorData(); 
    Producto pr1 = new Producto();
    ProductoData pr1Data = new ProductoData();

    DefaultTableModel modelo = new DefaultTableModel();
    

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /* Listar a los clientes*/
    public void listarClientes() {
        ArrayList<Cliente> listaC1 = clienteD.listarClientes();
        modelo = (DefaultTableModel) jTablaClientes.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < listaC1.size(); i++) {
            ob[0] = listaC1.get(i).getIdCliente();
            ob[1] = listaC1.get(i).getNombre();
            ob[2] = listaC1.get(i).getApellido();
            ob[3] = listaC1.get(i).getDomicilio();
            ob[4] = listaC1.get(i).getTelefono();
            modelo.addRow(ob);

        }
        jTablaClientes.setModel(modelo);
    }
        /* Listar a los proveedores*/
    public void listarProveedores() {
        ArrayList<Proveedor> listarP1 = proveedorD.listarProveedores();
        modelo = (DefaultTableModel) jTableProveedores.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i <listarP1.size(); i++) {
            ob[0] =listarP1.get(i).getIdProveedor();
            ob[1] = listarP1.get(i).getRazonSocial();            
            ob[2] = listarP1.get(i).getDomicilio();
            ob[3] = listarP1.get(i).getTelefono();
            modelo.addRow(ob);

        }
        jTablaClientes.setModel(modelo);
    }
      /* Listar a los productos*/
    public void listarProductos() {
        ArrayList<Producto> listarPr1 = pr1Data.listarProductos();
        modelo = (DefaultTableModel) jTableProductos.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i <listarPr1.size(); i++) {
            ob[0] =listarPr1.get(i).getIdProducto();
            ob[1] = listarPr1.get(i).getDescripcion();            
            ob[2] = listarPr1.get(i).getPrecioActual();
            ob[3] = listarPr1.get(i).getStock();
            modelo.addRow(ob);

        }
        jTableProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVentas1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelClientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idClienteC = new javax.swing.JTextField();
        nombreC = new javax.swing.JTextField();
        apellidoC = new javax.swing.JTextField();
        direcC = new javax.swing.JTextField();
        telC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaClientes = new javax.swing.JTable();
        btnGuardarClientes = new javax.swing.JButton();
        btnBuscarClientes = new javax.swing.JButton();
        btnEiminarClientes = new javax.swing.JButton();
        btnModificarClientes = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dProductoP = new javax.swing.JTextField();
        descP = new javax.swing.JTextField();
        precioActP = new javax.swing.JTextField();
        stockP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        btnBuscarClientes1 = new javax.swing.JButton();
        btnEiminarP = new javax.swing.JButton();
        btnModificarP = new javax.swing.JButton();
        btnGuardarP = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextIda_ventaV = new javax.swing.JTextField();
        jTextClienteV = new javax.swing.JTextField();
        jTextFechaV = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jRadioEstadoV = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextId_CompraC = new javax.swing.JTextField();
        jTextProveedorC = new javax.swing.JTextField();
        jTextFechaC = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idProveedorPV = new javax.swing.JTextField();
        razonSocialPV = new javax.swing.JTextField();
        domicilioPV = new javax.swing.JTextField();
        telPV = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        btnBuscarPV = new javax.swing.JButton();
        btnEliminarPV = new javax.swing.JButton();
        btnModificarPV = new javax.swing.JButton();
        btnGuardarPV = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnClientes.setBackground(new java.awt.Color(0, 102, 153));
        btnClientes.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(153, 204, 255));
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(0, 102, 153));
        btnProductos.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(153, 204, 255));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnCompra.setBackground(new java.awt.Color(0, 102, 153));
        btnCompra.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(153, 204, 255));
        btnCompra.setText("Compras");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(0, 102, 153));
        btnVentas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(153, 204, 255));
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(0, 102, 153));
        btnProveedores.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(153, 204, 255));
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_ch.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addGap(26, 26, 26)
                .addComponent(btnProductos)
                .addGap(29, 29, 29)
                .addComponent(btnProveedores)
                .addGap(35, 35, 35)
                .addComponent(btnVentas)
                .addGap(26, 26, 26)
                .addComponent(btnCompra)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 540));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sistema de gestión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 830, 70));

        btnVentas1.setBackground(new java.awt.Color(0, 102, 153));
        btnVentas1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnVentas1.setForeground(new java.awt.Color(153, 204, 255));
        btnVentas1.setText("Ventas");
        btnVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 420));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 420));

        jPanelClientes.setBackground(new java.awt.Color(0, 102, 153));
        jPanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setText("Cientes");
        jPanelClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 12, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanelClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 124, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanelClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 176, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("ID Cliente:");
        jPanelClientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("Dirección:");
        jPanelClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanelClientes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 284, -1, -1));

        idClienteC.setBackground(new java.awt.Color(0, 102, 153));
        idClienteC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        idClienteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteCActionPerformed(evt);
            }
        });
        jPanelClientes.add(idClienteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 78, 91, -1));

        nombreC.setBackground(new java.awt.Color(0, 102, 153));
        nombreC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        nombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCActionPerformed(evt);
            }
        });
        jPanelClientes.add(nombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 122, 91, -1));

        apellidoC.setBackground(new java.awt.Color(0, 102, 153));
        apellidoC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanelClientes.add(apellidoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 174, 91, -1));

        direcC.setBackground(new java.awt.Color(0, 102, 153));
        direcC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jPanelClientes.add(direcC, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 228, 91, -1));

        telC.setBackground(new java.awt.Color(0, 102, 153));
        telC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        telC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telCActionPerformed(evt);
            }
        });
        jPanelClientes.add(telC, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 282, 91, -1));

        jTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCliente", "Nombre", "Apellido", "Dirección", "Teléfono"
            }
        ));
        jTablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaClientes);
        if (jTablaClientes.getColumnModel().getColumnCount() > 0) {
            jTablaClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablaClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTablaClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablaClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTablaClientes.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanelClientes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 74, 493, 233));

        btnGuardarClientes.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/guardarico.png"))); // NOI18N
        btnGuardarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClientesActionPerformed(evt);
            }
        });
        jPanelClientes.add(btnGuardarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 348, -1, -1));

        btnBuscarClientes.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/buscarico.png"))); // NOI18N
        btnBuscarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });
        jPanelClientes.add(btnBuscarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 346, -1, -1));

        btnEiminarClientes.setBackground(new java.awt.Color(0, 102, 153));
        btnEiminarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/eliminarico.png"))); // NOI18N
        btnEiminarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEiminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEiminarClientesActionPerformed(evt);
            }
        });
        jPanelClientes.add(btnEiminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 347, -1, -1));

        btnModificarClientes.setBackground(new java.awt.Color(0, 102, 153));
        btnModificarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icocrear.png"))); // NOI18N
        btnModificarClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClientesActionPerformed(evt);
            }
        });
        jPanelClientes.add(btnModificarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 347, -1, -1));
        jPanelClientes.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 348, -1, -1));

        jTabbedPane1.addTab("Clientes", jPanelClientes);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel9.setText("Productos");

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("Id_Producto:");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setText("Descripción:");

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setText("Precio Actual:");

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setText("Stock:");

        dProductoP.setBackground(new java.awt.Color(0, 102, 153));
        dProductoP.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        descP.setBackground(new java.awt.Color(0, 102, 153));
        descP.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        precioActP.setBackground(new java.awt.Color(0, 102, 153));
        precioActP.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        stockP.setBackground(new java.awt.Color(0, 102, 153));
        stockP.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_producto", "Descripción", "Precio", "Stock"
            }
        ));
        jTableProductos.setPreferredSize(new java.awt.Dimension(400, 0));
        jScrollPane2.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableProductos.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableProductos.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnBuscarClientes1.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/buscarico.png"))); // NOI18N
        btnBuscarClientes1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientes1ActionPerformed(evt);
            }
        });

        btnEiminarP.setBackground(new java.awt.Color(0, 102, 153));
        btnEiminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/eliminarico.png"))); // NOI18N
        btnEiminarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEiminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEiminarPActionPerformed(evt);
            }
        });

        btnModificarP.setBackground(new java.awt.Color(0, 102, 153));
        btnModificarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icocrear.png"))); // NOI18N
        btnModificarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPActionPerformed(evt);
            }
        });

        btnGuardarP.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/guardarico.png"))); // NOI18N
        btnGuardarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stockP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dProductoP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioActP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnBuscarClientes1)
                .addGap(25, 25, 25)
                .addComponent(btnEiminarP)
                .addGap(31, 31, 31)
                .addComponent(btnModificarP)
                .addGap(24, 24, 24)
                .addComponent(btnGuardarP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dProductoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(descP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(precioActP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(stockP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarClientes1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnEiminarP))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnModificarP))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnGuardarP)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", jPanel4);

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(800, 420));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel11.setText("Ventas");

        jLabel22.setBackground(new java.awt.Color(0, 102, 255));
        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setText("Id_Venta:");

        jLabel23.setBackground(new java.awt.Color(0, 102, 255));
        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setText("Cliente:");

        jLabel24.setBackground(new java.awt.Color(0, 102, 255));
        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setText("Fecha:");

        jTextIda_ventaV.setBackground(new java.awt.Color(0, 102, 153));
        jTextIda_ventaV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextIda_ventaV.setText(" ");
        jTextIda_ventaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIda_ventaVActionPerformed(evt);
            }
        });

        jTextClienteV.setBackground(new java.awt.Color(0, 102, 153));
        jTextClienteV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextClienteV.setText(" ");
        jTextClienteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextClienteVActionPerformed(evt);
            }
        });

        jTextFechaV.setBackground(new java.awt.Color(0, 102, 153));
        jTextFechaV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Venta", "Cliente", "Fecha", "Estado"
            }
        ));
        jTableVentas.setPreferredSize(new java.awt.Dimension(400, 0));
        jScrollPane4.setViewportView(jTableVentas);
        if (jTableVentas.getColumnModel().getColumnCount() > 0) {
            jTableVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableVentas.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableVentas.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jRadioEstadoV.setBackground(new java.awt.Color(51, 102, 255));
        jRadioEstadoV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jRadioEstadoV.setText("Estado");
        jRadioEstadoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEstadoVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextIda_ventaV)
                                    .addComponent(jTextClienteV, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jTextFechaV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jRadioEstadoV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(62, 62, 62))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextIda_ventaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextClienteV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jRadioEstadoV)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));
        jPanel7.setPreferredSize(new java.awt.Dimension(800, 420));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel12.setText("Compras");

        jLabel26.setBackground(new java.awt.Color(0, 102, 255));
        jLabel26.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel26.setText("Id_Compra");

        jLabel27.setBackground(new java.awt.Color(0, 102, 255));
        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel27.setText("Proveedor");

        jLabel28.setBackground(new java.awt.Color(0, 102, 255));
        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel28.setText("Fecha");

        jTextId_CompraC.setBackground(new java.awt.Color(0, 102, 153));
        jTextId_CompraC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextId_CompraC.setText(" ");

        jTextProveedorC.setBackground(new java.awt.Color(0, 102, 153));
        jTextProveedorC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextProveedorC.setText(" ");
        jTextProveedorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProveedorCActionPerformed(evt);
            }
        });

        jTextFechaC.setBackground(new java.awt.Color(0, 102, 153));
        jTextFechaC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextFechaC.setText(" ");

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_Compra", "Proveedor", "Fecha"
            }
        ));
        jTableCompra.setPreferredSize(new java.awt.Dimension(400, 0));
        jScrollPane5.setViewportView(jTableCompra);
        if (jTableCompra.getColumnModel().getColumnCount() > 0) {
            jTableCompra.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableCompra.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableCompra.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(jLabel27)))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextId_CompraC)
                    .addComponent(jTextProveedorC)
                    .addComponent(jTextFechaC, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextId_CompraC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jTextProveedorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Compras", jPanel7);

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 420));

        jLabel10.setBackground(new java.awt.Color(51, 102, 255));
        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel10.setText("Proveedores");

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setText("Id_Proveedor");

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setText("Razón Social");

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel20.setText("Domicilio");

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setText("Teléfono");

        idProveedorPV.setBackground(new java.awt.Color(0, 102, 153));
        idProveedorPV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        idProveedorPV.setText(" ");
        idProveedorPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProveedorPVActionPerformed(evt);
            }
        });

        razonSocialPV.setBackground(new java.awt.Color(0, 102, 153));
        razonSocialPV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        razonSocialPV.setText(" ");

        domicilioPV.setBackground(new java.awt.Color(0, 102, 153));
        domicilioPV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        domicilioPV.setText(" ");

        telPV.setBackground(new java.awt.Color(0, 102, 153));
        telPV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        telPV.setText(" ");

        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_producto", "Razón Social", "Domicilio", "Teléfono"
            }
        ));
        jTableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProveedores);
        if (jTableProveedores.getColumnModel().getColumnCount() > 0) {
            jTableProveedores.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableProveedores.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableProveedores.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableProveedores.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnBuscarPV.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/buscarico.png"))); // NOI18N
        btnBuscarPV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPVActionPerformed(evt);
            }
        });

        btnEliminarPV.setBackground(new java.awt.Color(0, 102, 153));
        btnEliminarPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/eliminarico.png"))); // NOI18N
        btnEliminarPV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPVActionPerformed(evt);
            }
        });

        btnModificarPV.setBackground(new java.awt.Color(0, 102, 153));
        btnModificarPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icocrear.png"))); // NOI18N
        btnModificarPV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPVActionPerformed(evt);
            }
        });

        btnGuardarPV.setBackground(new java.awt.Color(0, 102, 153));
        btnGuardarPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/guardarico.png"))); // NOI18N
        btnGuardarPV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(telPV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idProveedorPV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(domicilioPV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(razonSocialPV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBuscarPV)
                                .addGap(25, 25, 25)
                                .addComponent(btnEliminarPV)
                                .addGap(31, 31, 31)
                                .addComponent(btnModificarPV)
                                .addGap(24, 24, 24)
                                .addComponent(btnGuardarPV)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel10)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idProveedorPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(razonSocialPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domicilioPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(telPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarPV)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnEliminarPV))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnModificarPV))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnGuardarPV))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedores", jPanel5);

        jTabbedPane2.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.addTab("Detalle Venta", jTabbedPane2);

        jTabbedPane3.setBackground(new java.awt.Color(51, 102, 255));
        jTabbedPane1.addTab("Detalle Compra", jTabbedPane3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:

        limpiarTabla();
        limpiarCliente();
        listarClientes();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnClientesActionPerformed
//botones del costado izquierdo______________________________________
    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        
        limpiarTabla();
        listarProveedores();       
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
       limpiarTabla();
        listarProveedores();       
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentas1ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed
//fin botones
    private void idClienteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteCActionPerformed

    private void idProveedorPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProveedorPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProveedorPVActionPerformed

    private void jTextIda_ventaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIda_ventaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIda_ventaVActionPerformed

    private void jTextClienteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextClienteVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextClienteVActionPerformed

    private void jTextProveedorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProveedorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProveedorCActionPerformed

    private void jRadioEstadoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEstadoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEstadoVActionPerformed

    private void telCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telCActionPerformed
//boton guardar cliente-------------------------------------------------
    private void btnGuardarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClientesActionPerformed
        if (!"".equalsIgnoreCase(nombreC.getText()) || !"".equalsIgnoreCase(apellidoC.getText())
                || !"".equalsIgnoreCase(direcC.getText()) || !"".equalsIgnoreCase(telC.getText())) {

            c1.setNombre(nombreC.getText());
            c1.setApellido(apellidoC.getText());
            c1.setDomicilio(direcC.getText());
            c1.setTelefono(telC.getText());
            clienteD.agregarCliente(c1);

            limpiarTabla();
            limpiarCliente();
            listarClientes();
            JOptionPane.showMessageDialog(null, "Cliente registrado");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarClientesActionPerformed

    private void nombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCActionPerformed

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClientesActionPerformed
//modificar Cliente
    private void btnModificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClientesActionPerformed

        if ("".equalsIgnoreCase(idClienteC.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione fila a modificar");

        } else {
            if (!"".equalsIgnoreCase(nombreC.getText()) || !"".equalsIgnoreCase(apellidoC.getText())
                    || !"".equalsIgnoreCase(direcC.getText()) || !"".equalsIgnoreCase(telC.getText())) {
                c1.setNombre(nombreC.getText());
                c1.setApellido(apellidoC.getText());
                c1.setDomicilio(direcC.getText());
                c1.setTelefono(telC.getText());
                c1.setIdCliente(Integer.parseInt(idClienteC.getText()));
                clienteD.modificarCliente(c1);

                limpiarTabla();
                limpiarCliente();
                listarClientes();

            } else {
                JOptionPane.showMessageDialog(null, "Algunos de los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarClientesActionPerformed

//Eliminar cliente
    private void btnEiminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEiminarClientesActionPerformed
        if (!"".equalsIgnoreCase(idClienteC.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Seguro desea eliminar?");
            if (pregunta == 0) {

                int id = Integer.parseInt(idClienteC.getText());
                clienteD.eliminarCliente(id);

                limpiarTabla();
                limpiarCliente();
                listarClientes();

            }
        }

    }//GEN-LAST:event_btnEiminarClientesActionPerformed

    private void jTablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaClientesMouseClicked

        int fila = jTablaClientes.rowAtPoint(evt.getPoint());
        idClienteC.setText(jTablaClientes.getValueAt(fila, 0).toString());
        nombreC.setText(jTablaClientes.getValueAt(fila, 1).toString());
        apellidoC.setText(jTablaClientes.getValueAt(fila, 2).toString());
        direcC.setText(jTablaClientes.getValueAt(fila, 3).toString());
        telC.setText(jTablaClientes.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_jTablaClientesMouseClicked

    private void btnBuscarClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClientes1ActionPerformed

    private void btnEiminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEiminarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEiminarPActionPerformed

    private void btnModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPActionPerformed
//boton guardar productos
    private void btnGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPActionPerformed
               if (!"".equalsIgnoreCase(descP.getText()) || !"".equalsIgnoreCase(precioActP.getText())
                || !"".equalsIgnoreCase(stockP.getText()) || !"".equalsIgnoreCase(estado.getText())) {

            pr1.setNombre(nombreC.getText());
            c1.setApellido(apellidoC.getText());
            c1.setDomicilio(direcC.getText());
            c1.setTelefono(telC.getText());
            clienteD.agregarCliente(c1);

            limpiarTabla();
            limpiarCliente();
            listarClientes();
            JOptionPane.showMessageDialog(null, "Cliente registrado");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarPActionPerformed

    private void btnBuscarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPVActionPerformed
//Eliminar proveedores 
    private void btnEliminarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPVActionPerformed
        if (!"".equalsIgnoreCase(idProveedorPV.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Seguro desea eliminar?");
            if (pregunta == 0) {

                int id = Integer.parseInt(idProveedorPV.getText());
                proveedorD.eliminarProveedor(id);

                limpiarTabla();              
                listarProveedores();

            }
        }
    }//GEN-LAST:event_btnEliminarPVActionPerformed
//modificar Proveedores
    
    private void btnModificarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPVActionPerformed
         if ("".equalsIgnoreCase(idProveedorPV.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione fila a modificar");

        } else {
            if (!"".equalsIgnoreCase(razonSocialPV.getText()) || !"".equalsIgnoreCase(domicilioPV.getText()) || !"".equalsIgnoreCase(telPV.getText())) {
                p1.setRazonSocial(razonSocialPV.getText());
               
                p1.setDomicilio(domicilioPV.getText());
                p1.setTelefono(telPV.getText());
                p1.setIdProveedor(Integer.parseInt(idProveedorPV.getText()));
                proveedorD.modificarProveedor(p1);

                limpiarTabla();
               
                listarProveedores();

            } else {
                JOptionPane.showMessageDialog(null, "Algunos de los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarPVActionPerformed
//guardar proveedor
    private void btnGuardarPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPVActionPerformed
       
        if (!"".equalsIgnoreCase(razonSocialPV.getText()) || !"".equalsIgnoreCase(domicilioPV.getText()) ||
                !"".equalsIgnoreCase(telPV.getText())) {

            p1.setRazonSocial(razonSocialPV.getText());
         
            p1.setDomicilio(domicilioPV.getText());
            p1.setTelefono(telPV.getText());
            proveedorD.agregarProveedor(p1);

            limpiarTabla();
           
            JOptionPane.showMessageDialog(null, "Registrado con éxito");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }

    }//GEN-LAST:event_btnGuardarPVActionPerformed
//tabla proveedores
    private void jTableProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProveedoresMouseClicked
        int fila = jTableProveedores.rowAtPoint(evt.getPoint());
        idProveedorPV.setText(jTablaClientes.getValueAt(fila, 0).toString());
        razonSocialPV.setText(jTablaClientes.getValueAt(fila, 1).toString());        
        domicilioPV.setText(jTablaClientes.getValueAt(fila, 2).toString());
        telPV.setText(jTablaClientes.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_jTableProveedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    private void limpiarCliente() {
        idClienteC.setText("");
        nombreC.setText("");
        apellidoC.setText("");
        direcC.setText("");
        telC.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoC;
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnBuscarClientes1;
    private javax.swing.JButton btnBuscarPV;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEiminarClientes;
    private javax.swing.JButton btnEiminarP;
    private javax.swing.JButton btnEliminarPV;
    private javax.swing.JButton btnGuardarClientes;
    private javax.swing.JButton btnGuardarP;
    private javax.swing.JButton btnGuardarPV;
    private javax.swing.JButton btnModificarClientes;
    private javax.swing.JButton btnModificarP;
    private javax.swing.JButton btnModificarPV;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVentas1;
    private javax.swing.JTextField dProductoP;
    private javax.swing.JTextField descP;
    private javax.swing.JTextField direcC;
    private javax.swing.JTextField domicilioPV;
    private javax.swing.JTextField idClienteC;
    private javax.swing.JTextField idProveedorPV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JRadioButton jRadioEstadoV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTablaClientes;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTable jTableProveedores;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextClienteV;
    private javax.swing.JTextField jTextFechaC;
    private javax.swing.JTextField jTextFechaV;
    private javax.swing.JTextField jTextId_CompraC;
    private javax.swing.JTextField jTextIda_ventaV;
    private javax.swing.JTextField jTextProveedorC;
    private javax.swing.JTextField nombreC;
    private javax.swing.JTextField precioActP;
    private javax.swing.JTextField razonSocialPV;
    private javax.swing.JTextField stockP;
    private javax.swing.JTextField telC;
    private javax.swing.JTextField telPV;
    // End of variables declaration//GEN-END:variables
}
